# Generated by Django 3.1.5 on 2021-01-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210126_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='change',
        ),
    ]
