# Generated by Django 3.1.5 on 2021-01-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210126_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='change',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
