# Generated by Django 3.1.5 on 2021-02-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img_path', models.CharField(default='img/default.png', max_length=150)),
                ('article', models.TextField(default='Hello, this is a default, empty article')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='none', max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codedmind_blog.article')),
            ],
        ),
    ]
