# Generated by Django 3.1.5 on 2021-02-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedmind_blog', '0002_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_path',
            field=models.CharField(default='img/default.png', max_length=150, unique=True),
        ),
    ]
