# Generated by Django 3.1.5 on 2021-02-03 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codedmind_blog', '0004_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 11, 42, 4, 950601, tzinfo=utc), verbose_name='date_published'),
        ),
    ]
